### ISSUE TITLE
Load data from Now to Infinity

### ISSUE THREAD

**Issue by belaazim** [couchbaselabs/java-dcp-client#10]
Hi,
I'm running this example https://github.com/couchbaselabs/java-dcp-client/blob/master/src/test/java/examples/PrintIncomingChanges.java

But I'm not getting the updtaes/changes triggered once my session is connected.

@daschl : could you please check this example ?
Thanks in advance.

**Comment by belaazim** [comment]
me again.
have you please any idea about which documents that their changes won't be detected by DCP ? I'm facing a strange behavior that I can't explain.
DCP is triggerring all update changes but for some documents on my data bucket this was not the case.

**Comment by daschl** [comment]
hmm I just stumbled across an issue as well where mutations are not printed.. can you do me a favour and try if the mutations are printed if you Start from BEGINNING instead of NOW/recover state?

**Comment by belaazim** [comment]
1. YES mutations are printed if you Start from BEGINNING instead of NOW (I just checked it)
2. For the case : Load data from Now to Infinity
   with which end sequence number do you request the stream?

**Comment by daschl** [comment]
for Infinitiy the end seqno is basically "-1", meaning no end.

**Comment by daschl** [comment]
@belaazim it could be you are running into a problem with rollbacks. Can you try the latest master version and check your log for warnings on rollback AND/OR set a breakpoint in the control handler if an event gets received?

**Comment by daschl** [comment]
if this is the case, here is an example on how to handle it (does not work on 0.2, needs master) https://github.com/couchbaselabs/java-dcp-client/blob/master/src/test/java/examples/PrintIncomingChanges.java#L59

**Comment by belaazim** [comment]
Good, with latest version with handling rollbacks, I received events for the changes for the previous documents.
But on starting session I'm getting all changes from begining Not from **Now**.
Could you please check ?

**Comment by daschl** [comment]
are you sure you get them from beginning and not at the rollback point? to which seqno did the server tell you to rollback to? 0?

**Comment by belaazim** [comment]
Probably you are right.
To confirm this is my log:

13:52:41.364 [main] INFO  com.couchbase.client.dcp.Client - Starting to Stream for 1024 partitions
13:52:41.817 [nioEventLoopGroup-2-2] WARN  com.couchbase.client.dcp.Client - Received rollback for vbucket 48 to seqno 0
13:52:41.817 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Stopping to Stream for 1 partitions
13:52:41.823 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Starting to Stream for 1 partitions
13:52:41.828 [nioEventLoopGroup-2-2] WARN  com.couchbase.client.dcp.Client - Received rollback for vbucket 56 to seqno 0
13:52:41.828 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Stopping to Stream for 1 partitions
13:52:41.829 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Starting to Stream for 1 partitions
13:52:41.840 [nioEventLoopGroup-2-2] WARN  com.couchbase.client.dcp.Client - Received rollback for vbucket 105 to seqno 0
13:52:41.840 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Stopping to Stream for 1 partitions
13:52:41.840 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Starting to Stream for 1 partitions
13:52:41.849 [nioEventLoopGroup-2-2] WARN  com.couchbase.client.dcp.Client - Received rollback for vbucket 143 to seqno 13
13:52:41.849 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Stopping to Stream for 1 partitions
13:52:41.849 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Starting to Stream for 1 partitions
13:52:41.875 [nioEventLoopGroup-2-2] WARN  com.couchbase.client.dcp.Client - Received rollback for vbucket 305 to seqno 0
13:52:41.875 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Stopping to Stream for 1 partitions
13:52:41.875 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Starting to Stream for 1 partitions
13:52:41.887 [nioEventLoopGroup-2-2] WARN  com.couchbase.client.dcp.Client - Received rollback for vbucket 390 to seqno 2
13:52:41.887 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Stopping to Stream for 1 partitions
13:52:41.887 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Starting to Stream for 1 partitions
13:52:41.914 [nioEventLoopGroup-2-2] WARN  com.couchbase.client.dcp.Client - Received rollback for vbucket 641 to seqno 6
13:52:41.915 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Stopping to Stream for 1 partitions
13:52:41.915 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Starting to Stream for 1 partitions
13:52:41.923 [nioEventLoopGroup-2-2] WARN  com.couchbase.client.dcp.Client - Received rollback for vbucket 747 to seqno 9
13:52:41.924 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Stopping to Stream for 1 partitions
13:52:41.924 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Starting to Stream for 1 partitions
13:52:41.932 [nioEventLoopGroup-2-2] WARN  com.couchbase.client.dcp.Client - Received rollback for vbucket 823 to seqno 0
13:52:41.932 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Stopping to Stream for 1 partitions
13:52:41.933 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Starting to Stream for 1 partitions
13:52:41.935 [nioEventLoopGroup-2-2] WARN  com.couchbase.client.dcp.Client - Received rollback for vbucket 831 to seqno 0
13:52:41.935 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Stopping to Stream for 1 partitions
13:52:41.935 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Starting to Stream for 1 partitions
13:52:41.993 [nioEventLoopGroup-2-2] WARN  com.couchbase.client.dcp.Client - Received rollback for vbucket 904 to seqno 0
13:52:41.993 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Stopping to Stream for 1 partitions
13:52:41.993 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Starting to Stream for 1 partitions
13:52:42.023 [nioEventLoopGroup-2-2] WARN  com.couchbase.client.dcp.Client - Received rollback for vbucket 994 to seqno 14
13:52:42.023 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Stopping to Stream for 1 partitions
13:52:42.024 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Starting to Stream for 1 partitions
13:52:42.027 [nioEventLoopGroup-2-2] WARN  com.couchbase.client.dcp.Client - Received rollback for vbucket 1005 to seqno 0
13:52:42.027 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Stopping to Stream for 1 partitions
13:52:42.027 [nioEventLoopGroup-2-2] INFO  com.couchbase.client.dcp.Client - Starting to Stream for 1 partitions
Rollback for partition 48 complete!
Rollback for partition 56 complete!
Rollback for partition 105 complete!
Rollback for partition 143 complete!
Rollback for partition 305 complete!
Rollback for partition 390 complete!
Rollback for partition 641 complete!
Rollback for partition 747 complete!
Rollback for partition 823 complete!
Rollback for partition 831 complete!
Rollback for partition 904 complete!
Rollback for partition 994 complete!
Rollback for partition 1005 complete!
Deletion: DeletionMessage [key: "Key_9", vbid: 48, cas: 1473847222119235585, bySeqno: 5, revSeqno: 5]
Mutation: MutationMessage [key: "Key_11", vbid: 56, cas: 1474445938458624000, bySeqno: 1, revSeqno: 1, flags: 0, expiry: 0, lockTime: 0, clength: 68]
Mutation: MutationMessage [key: "key_10:1", vbid: 105, cas: 1474445955912892416, bySeqno: 1, revSeqno: 1, flags: 0, expiry: 0, lockTime: 0, clength: 68]
Mutation: MutationMessage [key: "key_6", vbid: 143, cas: 1474444868679237632, bySeqno: 16, revSeqno: 16, flags: 0, expiry: 0, lockTime: 0, clength: 48]
Mutation: MutationMessage [key: "key_12", vbid: 305, cas: 1474461637170102272, bySeqno: 3, revSeqno: 3, flags: 0, expiry: 0, lockTime: 0, clength: 66]
Mutation: MutationMessage [key: "key_5", vbid: 390, cas: 1474444854569926656, bySeqno: 4, revSeqno: 4, flags: 0, expiry: 0, lockTime: 0, clength: 42]
Mutation: MutationMessage [key: "key_4", vbid: 641, cas: 1474444623997435904, bySeqno: 7, revSeqno: 7, flags: 0, expiry: 0, lockTime: 0, clength: 42]
Mutation: MutationMessage [key: "key_1", vbid: 747, cas: 1474446122687332352, bySeqno: 13, revSeqno: 13, flags: 0, expiry: 0, lockTime: 0, clength: 44]
Deletion: DeletionMessage [key: "key_8", vbid: 823, cas: 1473847070542266369, bySeqno: 5, revSeqno: 5]
Mutation: MutationMessage [key: "key_10", vbid: 831, cas: 1474461607713177600, bySeqno: 12, revSeqno: 12, flags: 0, expiry: 0, lockTime: 0, clength: 67]
Mutation: MutationMessage [key: "key_7", vbid: 904, cas: 1474461660531458048, bySeqno: 17, revSeqno: 17, flags: 0, expiry: 0, lockTime: 0, clength: 82]
Mutation: MutationMessage [key: "key_2", vbid: 994, cas: 1474444567949410304, bySeqno: 16, revSeqno: 16, flags: 0, expiry: 0, lockTime: 0, clength: 42]
Mutation: MutationMessage [key: "key_12:1", vbid: 1005, cas: 1474446262630350848, bySeqno: 1, revSeqno: 1, flags: 0, expiry: 0, lockTime: 0, clength: 68]

**Comment by daschl** [comment]
yeah it needs to roll back those partitions since it doesn't have the specified seqnos anymore for some reason.

**Comment by belaazim** [comment]
so is there a way to force it to start from **Now** not from **rollback point** ?

**Comment by daschl** [comment]
I'm not sure why it is happening actually, can you send me a full debug log of the output? My email addy is firstname.lastname@couchbase.com

**Comment by belaazim** [comment]
in my previous message I sent you the full log printed to console.
is there another log produced by the DCP Client ?

**Comment by daschl** [comment]
yes, can you set the log level to DEBUG and then rerun?

**Comment by belaazim** [comment]
[dcpClient.txt](https://github.com/couchbaselabs/java-dcp-client/files/485404/dcpClient.txt)

**Comment by daschl** [comment]
@belaazim 0.3.0 released, just FYI

**Comment by belaazim** [comment]
@daschl  thanks for the notification :)
did this version fixed the problem reported ?

**Comment by daschl** [comment]
I'm not sure, but upgrading brings other benefits and if there is something to fix anyways I'll do it on master

**Comment by daschl** [comment]
Note that I'll only get back to DCP next week due to other work, but I'll let you know as soon as I find anything useful

**Comment by belaazim** [comment]
ok thanks

**Comment by avsej** [comment]
Issue with rollbacks has been fixed in https://github.com/couchbaselabs/java-dcp-client/commit/24c54ffac149b43076d3402a5a235bf5e63ceecc

@belaazim you can rebuild snapshot from master and check

**Comment by belaazim** [comment]
@avsej : I tested this fix and it is Ok.
Thanks !
When do you plan to provide a release 0.4.0 ?

**Comment by daschl** [comment]
0.4.0 already released! (maven central may need a bit of time to sync)
