### ISSUE TITLE
Question: RxJava API

### ISSUE THREAD

**Issue by jacek99** [couchbaselabs/java-dcp-client#2]
Sorry for opening an issue to ask a question, but are there any plans to add an RxJava API, to be consistent with the rest of the Java SDK?

Would probably make it also easier to consume the stream of events as they are coming in,

Thank you

**Comment by avsej** [comment]
For the first iteration, we want to bring less abstractions, and consume everything as fast as possible. But eventually it might be added.

**Comment by jacek99** [comment]
Understood. We will try to integrate with the current API then,

Is there an ETA as to when it will start getting pushed to Maven Central so that we can consume it more easily as a dependency?

Thank you

**Comment by jacek99** [comment]
Also, is there a limit to how many DCP clients one can have per cluster?
Would 50 be still acceptable listening to ALL vbuckets across a 3-node cluster?

**Comment by daschl** [comment]
@jacek99 wow you are an early adopter! :)

once the rebalance works and you can consume/resume from a session state we'll certainly release a 0.1 release (which we'd consider the MVP I think).

I don't want to expose too much RxJava APIs right now and keep it low level, also for the reason its very easy to create an observable from the callback (you can use a subject for example). Let me know if you need help on this.

Also, you should not create too many dcp clients per cluster! The more you do the more load it puts on the server - if you need that many I'd rather recommend you use something like the kafka connector and consume from kafka or so - or you just expose your own stream through some other external system.

What use case do you have in mind?

**Comment by daschl** [comment]
So for example you could use this simplified mechanism here, of course you need more orchestration for advanced use cases :)

``` java
final PublishSubject<ByteBuf> subject = PublishSubject.create();

client.dataEventHandler(new DataEventHandler() {
    @Override
    public void onEvent(ByteBuf event) {
        if (subject.hasObservers()) {
            subject.onNext(event);
        } else {
            event.release();
        }
    }
});
```

**Comment by daschl** [comment]
I'll close this one out for now since we're not in the near term planning to add it to the main interfaces, but as you can see above its very easy to do so. Feel free to open new issues if you run into specific things - and thanks much for testing!
