### ISSUE TITLE
tomcat clearReferencesThreads fails cause of not stopped DCP threads

### ISSUE THREAD

**Issue by belaazim** [couchbaselabs/java-dcp-client#24]
Hi,
I'm getting a list of issues while shutdowing my web application using DCP clients.
@daschl  : Any idea about this please ?

oct. 19, 2016 4:10:57 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
GRAVE: The web application [/hello] **appears to have started a thread named [Thread-2] but has failed to stop it. This is very likely to create a memory leak**.
oct. 19, 2016 4:10:57 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
GRAVE: The web application [/hello] appears to have started a thread named [SimplePauseDetectorThread_0] but has failed to stop it. This is very likely to create a memory leak.
oct. 19, 2016 4:10:57 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
GRAVE: The web application [/hello] appears to have started a thread named [SimplePauseDetectorThread_1] but has failed to stop it. This is very likely to create a memory leak.
oct. 19, 2016 4:10:57 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
GRAVE: The web application [/hello] **appears to have started a thread named [SimplePauseDetectorThread_2] but has failed to stop it.** This is very likely to create a memory leak.
oct. 19, 2016 4:10:57 PM org.apache.coyote.AbstractProtocol stop

**Comment by daschl** [comment]
how are you performing the shutdown of the sdk?

**Comment by belaazim** [comment]
in this way : 
bucket.disconnect();
cluster.disconnect();
envCouchbase.shutdownAsync().toBlocking().single();
Schedulers.shutdown();
is something missing or incorrect ?

**Comment by avsej** [comment]
do you call disconnect on the `Client` object?
https://github.com/couchbaselabs/java-dcp-client/blob/7231584d9247f40af1c27d84d22bda4b6ae6cbc1/src/main/java/com/couchbase/client/dcp/Client.java#L299-L309

**Comment by belaazim** [comment]
yes, in this way: 
client.stopStreaming().await(); 
client.disconnect().await();

**Comment by belaazim** [comment]
Hi,
I find it :)
It misses for sdk shutdown:  LatencyStats.getDefaultPauseDetector().shutdown();

**Comment by daschl** [comment]
on which SDK version are you on? (java-client). we fixed a leak in a recent version

**Comment by belaazim** [comment]
I'm using 2.3.3 java-client (with DCP client version 0.4.0)

**Comment by daschl** [comment]
@belaazim JVMCBC-368 got fixe din 2.3.4, can you try that one? Also dcp-client is now on 0.6.0, but if you pick it up make sure to acknowledge the snapshot marker on the control handler if you are using the buffering.

**Comment by belaazim** [comment]
how to use the buffering ? in which case ?
How to make sure to acknowledge the snapshot ?

**Comment by daschl** [comment]
@belaazim https://github.com/couchbaselabs/java-dcp-client/blob/master/README.md#flow-control

**Comment by belaazim** [comment]
Thanks @daschl
