### ISSUE TITLE
Specific scenario for persisted State

### ISSUE THREAD

**Issue by belaazim** [couchbaselabs/java-dcp-client#29]
Hello,

I'm defining a specific scenario using persisted State feature.

The steps of this scenarios are: 
1. client.recoverOrInitializeState(StateFormat.JSON, persisted, **StreamFrom.BEGINNING**, **StreamTo.NOW)**.await();
2. wait until state is ended
2. persist state on a file
3. some instructions on previously received messages ..... 
4.  client.recoverOrInitializeState(StateFormat.JSON, persisted, **StreamFrom.BEGINNING**, **StreamTo.INFINITY**).await();

The problems are : 
* step 1 if a persisted file doesn't exist : it is OK it reads the full databucket snapshot.
  if a persisted file exist. it dosen't recocver databucket document updates done after the persisting state stored on the file.
*  any update of any databucket document is no more detectable (no mutation event) after step 4.

I'm using java DCP client version 0.6.0 and its adqueate dependencies.

@avsej @daschl  : any idea please ?

Thanks in advance.

**Comment by belaazim** [comment]
@avsej  @daschl  

I'm coming back with a code example to produce the error: (tested with 0.7.0 dcp client version)

```java
        static String BUCKET = "default";
	static String FILENAME = "state-" + BUCKET + ".json";
	static int tradeNumber = 0 ;

	public static void main(String[] args) throws Exception {
		// Connect to localhost and use the default bucket
		final Client client = Client.configure()
				.hostnames("localhost")
				.bucket(BUCKET)
				.controlParam(DcpControl.Names.CONNECTION_BUFFER_SIZE, 10240) // set the buffer to 10K
				.bufferAckWatermark(75) // after 75% are reached of the 10KB, acknowledge against the server
				.build();

		client.controlEventHandler(new ControlEventHandler() {
			public void onEvent(ByteBuf event) {
				if (DcpSnapshotMarkerRequest.is(event)) {
					client.acknowledgeBuffer(event);
				}
				event.release();
			}
		});


		client.dataEventHandler(new DataEventHandler() {
			public void onEvent(ByteBuf event) {
				String key = DcpMutationMessage.key(event).toString(CharsetUtil.UTF_8);				    
				if (DcpMutationMessage.is(event) && key.matches("Trade_.*:.*")) {
					tradeNumber = tradeNumber + 1;
					System.out.println("Mutation: " + key +  " : " + tradeNumber);

				} 
				client.acknowledgeBuffer(event);
				event.release();
			}
		});

		// Connect the sockets
		client.connect().await();

		// Try to load the persisted state from file if it exists
		File file = new File(FILENAME);
		byte[] persisted = null;
		if (file.exists()) {
			FileInputStream fis = new FileInputStream(FILENAME);
			persisted = IOUtils.toByteArray(fis);
			fis.close();
		}


		streamFromBeginToNow(client, persisted);
		updateDoc(BUCKET, "Test-CB");
		streamFromPersistedToInfinity(client,persisted);
	}

	private static void streamFromBeginToNow(Client client, byte[] persisted) throws IOException{	
		System.out.println(System.currentTimeMillis() + " - Start Streaming from Begining or Persisted State if exists to Now! ");
		client.recoverOrInitializeState(StateFormat.JSON, persisted, StreamFrom.BEGINNING, StreamTo.NOW).await();
		client.startStreaming().await();

		while(true) {
			if (client.sessionState().isAtEnd()) {
				break;
			}
			try {
				Thread.sleep(500);
			} catch (InterruptedException e) {
			}
		}

		System.out.println(System.currentTimeMillis() + " - State stopped on Now ");

		byte[] state = client.sessionState().export(StateFormat.JSON);

		// Write it to a file
		FileOutputStream output = new FileOutputStream(new File(FILENAME));
		IOUtils.write(state, output);
		output.close();

		System.out.println(System.currentTimeMillis() + " - Persisted State! ");

		client.stopStreaming().await();	
		client.disconnect();

		System.out.println(System.currentTimeMillis() + " - Stop streaming ! ");
	}

	private static void streamFromPersistedToInfinity(Client client, byte[] persisted){
		System.out.println(System.currentTimeMillis() + " - Start Streaming from Persisted State if exists to No End! ");
		client.connect().await();
		client.recoverOrInitializeState(StateFormat.JSON, persisted, StreamFrom.NOW, StreamTo.INFINITY).await();
		client.startStreaming().await();

		try {
			Thread.sleep(900);
		} catch (InterruptedException e) {
		}

		System.out.println(System.currentTimeMillis() + " - Streaming ongoing! ");
	}

	private static void updateDoc(String bucketname, String DocId){
		System.out.println(DocId + " has been inserted in Couchbase Bucket " + bucketname);
		CouchbaseCluster cluster = CouchbaseCluster.create("localhost");
		Bucket bucket = cluster.openBucket(bucketname);
		bucket.upsert(JsonDocument.create(DocId, JsonObject.create().put("uuid", UUID.randomUUID().toString())));
	}
```

**Comment by belaazim** [comment]
The code example above:
* start streaming from begining to now ( use the default bucket) 
=> Mutation messages are displayed
* once we got end state of previous session ; we **persiste** the state on a file.
* stop streaming ; disconnect client
* insert/update a doc with key **"Test-CB"** on default bucket
* start streaming from persisted state to no end
=> Expected result :  Mutation message about **"Test-CB"**  update 
=> But it Mutation Message is NOT DISPLAYED !! Problem

**Comment by belaazim** [comment]
@avsej @daschl : could you please try the code above and check how it could be fixed to get expected results ?
Thanks in advance,

**Comment by avsej** [comment]
Thanks @belaazim, I will try and get back here

**Comment by belaazim** [comment]
any news ? did you succeed to reproduce the problem.

**Comment by ingenthr** [comment]
Just to update you @belaazim, @avsej talked about this in a review earlier this morning.  We believe the problem comes about because we're missing the storage of some state info in the `sessionState`.  It's an acknowledged issue.  The bug slipped through as we handle state management differently in some of the higher level frameworks say with the Kafka Connector.

**Comment by belaazim** [comment]
Hi all,
@ingenthr , @avsej  Thanks for the explanation and the time you provide for this issue.
Do you have please any news about it ?
Best regards,
Maherzia

**Comment by belaazim** [comment]
Hi all,
@ingenthr , @avsej, @daschl : any updates please about this issue ?
saving/restarting from a specific state is critical for our application.
Thanks for your help

**Comment by dnault** [comment]
The java-dcp-client project is being promoted from couchbaselabs to the primary couchbase org. As part of this change, issues reported via GitHub are being migrated to the Couchbase Jira.

To track the progress of this issue, please follow https://issues.couchbase.com/browse/JDCP-59
