### ISSUE TITLE
Some questions : session State / Message Filter

### ISSUE THREAD

**Issue by belaazim** [couchbaselabs/java-dcp-client#3]
Hi,  
Some questions :
1. Is there a way to check if a DCP MutationMessage is a creation message or an update message ?
2. How to initialize the session state to stream from from last session disconnect ?

Example,
run connection - stop connection - < Some Updates On COUCHBASE Done > - restart connection

I need to just get < Some Updates On COUCHBASE Done > between the stop and the restart.
Not to getting changes from beginning

**Comment by daschl** [comment]
wrt to 1) I checked with our Server engineers and this is not possible with DCP at the Moment, so you Need to handle this in your Code for now. What is your use case?

on 2) once I have the new stuff committed it should work quite easy - I'll see if I can add an example as well.

**Comment by daschl** [comment]
I'll Close this one since for 2) is tracked in #5 , lets discuss there.
