### ISSUE TITLE
A question about Dcp Messages

### ISSUE THREAD

**Issue by belaazim** [couchbaselabs/java-dcp-client#32]
Hi 
could you please share more details about Dcp Messages when they occurs exactly : 
1. DcpDeletionMessage : when a document is deleted
2. DcpExpirationMessage : ??
3. DcpMutationMessage : when a document is updated
4. DcpSnapshotMarkerMessage: ??
5. DcpStateVbucketStateMessage: ??
6. DcpStreamEndMessage ??

Thanks in advance,

**Comment by nnanda2016** [comment]
In CB, you can create a document with a TTL (Time to Live). Once TTL expires the document is removed automatically by CB. This is when `DcpExpirationMessage` event is produced.

`DcpMutationMessage` is for both create and update scenario.

I am not sure about others. However, I am interested to know about those. The API Doc does not talk much.

**Comment by avsej** [comment]
Currently server does not send expiration message, so in this case it will be still [Deletion message](https://github.com/couchbaselabs/dcp-documentation/blob/master/documentation/commands/deletion.md). [Snapshot message](https://github.com/couchbaselabs/dcp-documentation/blob/master/documentation/commands/snapshot-marker.md) needed to notify about snapshot boundaries before transferring the snapshot. [End message](https://github.com/couchbaselabs/dcp-documentation/blob/master/documentation/commands/stream-end.md) is signal from the server that there won't be any data for the stream.

All possible protocol messages described here:
https://github.com/couchbaselabs/dcp-documentation/tree/master/documentation/commands

**Comment by belaazim** [comment]
Thanks for these details @nnanda2016  and @avsej
