### ISSUE TITLE
System event messages dropped through default EventBus

### ISSUE THREAD

**Issue by Maxdamantus** [couchbaselabs/java-dcp-client#33]
By default, `ClientEnvironment` constructs a `DefaultEventBus` (from couchbase-jvm-core) object to wrap around the subject used for system messages (passed to the library user using the `systemEventHandler` callback). `DefaultEventBus.get()` uses `.onBackpressureDrop()` to avoid backpressure situations, which doesn't seem desirable here; it should not drop things like `StreamEndEvent`s which will never be sent again.

**Comment by avsej** [comment]
Moved to issue tracker: https://issues.couchbase.com/browse/JDCP-48
