### ISSUE TITLE
Partitions initialized with StreamTo.INFINITY are skipped

### ISSUE THREAD

**Issue by dak369** [couchbaselabs/java-dcp-client#35]
In the commit date March 23, 2017, in the selectInitializedPartitions method this comparison was added: ps.getStartSeqno >= ps.getEndSeqno to detect uninitialized partitions. The value for EndSeqno when initialized with StreamTo.INFINITY is -1, and then this comparison fails and the partition is considered uninitialized. Thanks!

**Comment by avsej** [comment]
Thank you for report. I've moved it to issue tracker: https://issues.couchbase.com/browse/JDCP-53
