### ISSUE TITLE
client.connect().await() never returns 

### ISSUE THREAD

**Issue by belaazim** [couchbaselabs/java-dcp-client#45]
Hi,
client.connect().await() never returns and keep blocked.
Have you please in idea in which case this could be happen ?

**Comment by dnault** [comment]
Unfortunately I'm unable to answer your question; there's not enough information here to determine the cause of the problem.

For assistance using the DCP client, I would refer you to the Couchbase forums at https://forums.couchbase.com

If you believe you have discovered a bug in this library, please file an issue on the Couchbase Jira at https://issues.couchbase.com/projects/JDCP/ including a small code sample or the steps required to reproduce the issue.

Thanks!
