### ISSUE TITLE
dcp client plan

### ISSUE THREAD

**Issue by belaazim** [couchbaselabs/java-dcp-client#5]
Hi,
When are you planning to include these features:
1. Export current session state for durability
2. Start from specific session state (import durable state)
   ?

**Comment by daschl** [comment]
@belaazim I added it today, right now with simple JSON byte[] import and export. I didn't have time yet to come up with examples but at every point in time you can call `byte[] state = client.sessionState().toJson();`  and persist it.. and when the app starts you take the byte[] and instead of initFrom\* you call initFromJson() with it and then start streaming.

**Comment by belaazim** [comment]
I didn't find an implementation of initFromJson() ?

**Comment by daschl** [comment]
woops, I didn't commit it yet.. I'll do asap, maybe check back tomorrow :)

**Comment by daschl** [comment]
committed the changes right now, you can find the `initFromJson` on the client.

**Comment by belaazim** [comment]
Thanks for quick commit.
I stored the state as you explained. Then stop connecting to dcp client. 
I do some modification on my couchBase documents.
I connect again, but this time I restored the state. and I launch the client.initFromJson(state);
The modification between the stop and the reconnect using (restore state) was not detected.
More then, If I do any change on couchbase documents this was not detected too.
It seems no listening to changes
Maybe something misses from the commit :)

**Comment by daschl** [comment]
can you please share your code so I can reproduce it?

**Comment by belaazim** [comment]
I'm using the same code you are describing in readme.

## 1. DCP Client load data from begining and Store State

client.connect().await();
// Initialize the session state to stream from 0 to infinity
client.initFromBeginningToNoEnd().await();
// Start streaming on all partitions
client.startStreams().await();  
// Wait for 1 min  
long endTime = System.nanoTime() + TimeUnit.NANOSECONDS.convert(1L, TimeUnit.MINUTES);
        while ( System.nanoTime() < endTime ){
          ;
        }
// Store state in a file
byte[] state = client.sessionState().toJson();
storeState(state);
// Shut down once done.
client.disconnect().await();

## 2. DCP Client load data from specific State

// Connect to the cluster
client.connect().await();
// restore state from the previous file  
byte[] state = restoreState();
client.initFromJson(state);
// Start streaming on all partitions
client.startStreams().await();
while(true) {
  Thread.sleep(1000);
    ;
}

**Comment by belaazim** [comment]
I find my error 
I must use client.initFromJson(state).await();
instead of
client.initFromJson(state);
It works fine ! thanks a lot :)

**Comment by daschl** [comment]
awesome!! :) can we close this one then?
