### ISSUE TITLE
Strange behavior with restore state

### ISSUE THREAD

**Issue by belaazim** [couchbaselabs/java-dcp-client#6]
Hi
I connect to CouchBse using DCP client. I save the session state.
I disconnect.
I do some update (change of a document's content) on couchbase documents.
I restart with init from Json.
The changes between the stop and the reconnection was not recovered.
Any idea about this ?
Note: If the change is about adding a new document from scratch. it is recovered.

**Comment by daschl** [comment]
@belaazim can you provide an example? btw be aware I'm releasing 0.2.0 today which has slightly different API. check out the examples in the test directory, I also added more javadocs to the client.

**Comment by daschl** [comment]
here is an example https://github.com/couchbaselabs/java-dcp-client/blob/master/src/test/java/examples/StatePersistence.java

**Comment by belaazim** [comment]
@daschl thanks for your support.
I'm trying today to test the StatePersistence example.
I'm getting this exception: 
Exception in thread "main" java.lang.NoSuchMethodError: com.couchbase.client.core.config.CouchbaseBucketConfig.nodeIndexForMaster(IZ)S 
com.fis.integ.core.publisher.sol2.StatePersistence.main(StatePersistence.java:71)
Have you please any idea about this ?

**Comment by daschl** [comment]
@belaazim is your current problem solved with 0.2 and the example?

**Comment by belaazim** [comment]
@daschl Thanks for your help.
I'm testing today your new commit using the State Pesistence example.
I tested it with a small data bucket (6 documents) : it works like a charm.
But with a bigger data bucket (450 documents). when I stop the session and I do some modifications on some documents and I reconnect with persissted session it doesn't recover the updates (between stop and restart) more then any other update during the session is not detected.
Is it related to data bucket size ?
I'm replaying the test in order to be sure ... keep you informed ...

**Comment by belaazim** [comment]
A scenario that causes problem (on both small and big data bucket):
1. start session
2. save session
3. create new docment (that has been recently removed)!! 
4. restart session
5.  => not stable behavior
Could you reproduce it ?
I'm pretty sure that once we add a document which was not added from the beginning  ; the changes to this document are not stored or detected ... to check maybe from your side

**Comment by daschl** [comment]
Okay I'll try to reproduce this case. What should happen in theory is that it is on the sequence number from before the mutation so DCP will stream it after the fact.

Are you against localhost or a multi node cluster?

**Comment by belaazim** [comment]
against localhost (one node cluster)

**Comment by daschl** [comment]
Okay cool do you by chance have code to reproduce? If not I'll try to come up with something similar.

**Comment by belaazim** [comment]
For code I'm using StatePersistence.java :)

**Comment by daschl** [comment]
@belaazim I just tried out a slightly changed version of state persistence (https://gist.github.com/daschl/e00689955e2b34f80e511b512929d0dc), the only change being that after 10 times persisting it stops. I have the workload generator running in paralell, storing a doc every second. so after the code exists and I start again it automatically starts from where it was last persisted.

If this is not what you are seeing, what happens exactly? thanks for helping me track this down :)

**Comment by belaazim** [comment]
Your session is stoped. You have a json *\* file persisting your session. 
Ok now please follow these steps.
Add a new document (key-1) in your data bucket.
change a field in this new document (key-1) . 
Choose an other old document and update it.
Now restart your session which will recover state from**.
You won't get changes of document (key-1) these changes are missing :( 
could you please try this ?

**Comment by daschl** [comment]
Okay so I tried that and I think I saw the correct behavior, but there is a subtle thing to it, maybe you ran into this: the server performs deduplication so you are not seeing all changes. So for example I stopped the state.

Then I created a document with

``` json
{
  "old": "maybe"
}
```

after save I changed it to 

``` json
{
  "old": "yes!"
}
```

and as soon as I restarted the stream I only saw:

```
Mutation: MutationMessage [key: "new-doc", vbid: 54, cas: 957568525533184, bySeqno: 3, revSeqno: 3, flags: 0, expiry: 0, lockTime: 0, clength: 20]
{
  "old": "yes!!"
}
```

So no sign of the intermediate representation. But this is similar to lets say you are deleting this state.json file and start from the beginning. You still won't see all the mutations one document is going through, but rather only the latest.

Is this also what you are seeing or is this different?

**Comment by belaazim** [comment]
Not Able to define exactly the scenario causing this behavior.
Sometimes I get latest mutation sometimes no changes detected.

If the added document was recently deleted, the random behavior is reproduced.
This scenario:
1. delete the doc with **new-doc**
2. create the doc with **new-doc** and keep the same content
3. update the doc **new-doc**

restart the session => the latest mutation is no more reported.

**Comment by daschl** [comment]
hm I tried the exact same scenario, and in my case the only thing reported is the latest mutation, I don't see the delete or the recreation as mutations.

**Comment by daschl** [comment]
@belaazim I think at this point do you think there is a way you can record a screen demo or provide some code where you can reproduce this? You can include the java-client too in the code so that it runs the mutations in parallel, I can show you how to do this if you need assistance.

**Comment by belaazim** [comment]
@daschl : 
Thanks for your help !
 I'll try to do it before the end of this week. maybe I'll need your assistance.

**Comment by daschl** [comment]
sure, let me know where I can help.. I might kick out a 0.3 release in the meantime but if we find a bug we can fix it for the next release.

**Comment by daschl** [comment]
@belaazim does this also work as expected with 0.4 or is there still an issue?

**Comment by belaazim** [comment]
@daschl sorry for the late of my answer.
I tested with a quick example it seems OK with 0.4 version.
