### ISSUE TITLE
please add state export to String not only to byte[]

### ISSUE THREAD

**Issue by igreenfield** [couchbaselabs/java-dcp-client#7]
if I want to save the state in some other persistent it will help

**Comment by daschl** [comment]
@igreenfield I intentionally chose byte[] since it allows us in the future to also export to efficient binary representations. If you use the JSON export, feel free to use new String(bytes, "UTF-8");

**Comment by igreenfield** [comment]
but why not to add another option?

**Comment by daschl** [comment]
can you describe why you need it as a string instead of a byte array?

**Comment by igreenfield** [comment]
I want to save it in the DB.... and for debugging it mach easy if it stored as String

**Comment by daschl** [comment]
well, technically a string is a byte[] is just the encoded representation - so when you write it to the database it needs to turn the string back into a byte[] eventually, right?

I get the point that you are looking for something easier, but I don't think a `exportAsString(StateFormat)` buys you much more than a `new String(export(..), "UTF-8")`. Also if we add a String API we need to add more logic to make sure that the state format is actually representable as a string.

**Comment by igreenfield** [comment]
you are using Jackson for the serialization so it can return string instead of byte[]

**Comment by daschl** [comment]
Okay, maybe I didn't get my point across :) I want to keep this APIs generic over the way we serialize and unserialize the state so in the future we can add more representations. Right now its only JSON so you are right, but if we add a binary format then exporting it as a string makes no sense at all. Since this is such a low level library I want to keep it as lean as possible, and this includes a tight focus on exported APIs.

Do you think for your use case you can wrap it with String and be good with it?

**Comment by igreenfield** [comment]
Even if the state will be binary you always could represent is as string (base64 for sample).

so you can add `StateFormat.JSON_String,  StateFormat.JSON_BYTE` and so on...
and in the deserialization also use this to know how to do it.

for now I can do that but the API is very UGLY this way...

**Comment by daschl** [comment]
Okay, I don't agree with your assessment that the API is ugly. Also, many other projects that we are currently working on (kafka, spark, internal stuff,...) are fine using the API as is and we didn't find problems (they don't attempt to convert it to a string but rather treat is as a black box. If you want to log its just one constructor of String away).

For now I don't think we'll add it, if the use case comes up more often from other users I'll of course consider adding it.
