### ISSUE TITLE
How to change state after startStreaming

### ISSUE THREAD

**Issue by igreenfield** [couchbaselabs/java-dcp-client#8]
If I have client that is already streaming can I change it's state?

**Comment by daschl** [comment]
yeah so in theory the state always changes as mutations come in, but I would expect it become kind of hairy depending on what you want to do. What is your use case?

What is a little safer is you can always stop streams, alter the state (lets say to a backup persisted) and then start the streams again, this should pick up where you left off.

**Comment by igreenfield** [comment]
the second option is good for me... how I can stop the streaming?

**Comment by daschl** [comment]
the client has "stopStreaming" methods, like "startStreaming". You can do it for all of them (no arg) or just a subset of the partitions (provide the vararg list of partition indexes)

**Comment by igreenfield** [comment]
is it safe to call connect multiple times?

**Comment by daschl** [comment]
hm, currently there are no test for that situation, I'd say in the future we should aim for it to be safe but right now I don't think so.

**Comment by igreenfield** [comment]
ok thanks

**Comment by igreenfield** [comment]
can I know if the client is connected?

**Comment by daschl** [comment]
I created a ticket for the multiple connect attempts: https://issues.couchbase.com/browse/JDCP-12

hmm right now we do not expose a method to check if "is connected", since its not clear what it means in the first place. I can expose something like that on the API, can you give me a use case what you are trying to do?

**Comment by igreenfield** [comment]
1. if multi connect is safe so no need to check if connected.
2. I try to resync to current location: I have 2 servers that sync one is master and the other is salve and if the master failed the slave should continue from the last check point the master left on the DB.

**Comment by daschl** [comment]
so both master and slave are streaming in parallel? Wouldn't you just start the stream on the slave when the master fails?

**Comment by igreenfield** [comment]
each node save cache of data for using so if I start only on failure the slave won't have the cache....

**Comment by daschl** [comment]
Okay in this case the strategy we discussed makes sense. Only beware that if your slave is ahead of the master then you need to implement some app-level rollback, unless you prohibit that with some kind of coordination mechanism between the master and slaves.

**Comment by igreenfield** [comment]
OK thanks!!!

**Comment by daschl** [comment]
cool, let me know if you run into issues with it

**Comment by daschl** [comment]
@igreenfield 0.3.0 released, just FYI
