### ISSUE TITLE
How to stop streaming with State <StreamFrom.BEGINNING,StreamTo.NOW>

### ISSUE THREAD

**Issue by belaazim** [couchbaselabs/java-dcp-client#9]
Hi,
I configured my client as follow : client.initializeState(StreamFrom.BEGINNING, StreamTo.NOW).await();
I need to stop streaming and disconnect the client once the streaming is no more available [ended by StreamTo.NOW ].
Any Idea about this ?

**Comment by belaazim** [comment]
I find it.

int count = 0 ;
        while ( count < 1024){
            count = 0;
            for(short i=0; i<1024; i++){
                if ( ! client.streamIsOpen(i) ){
                    count ++;
                }
            }
        }
        client.stopStreaming().await();
        client.disconnect();
Is it ok ? or is there any risk with this method ?
May be this could be implemented in another way on DCP client ?

**Comment by daschl** [comment]
This example shows how :) https://github.com/couchbaselabs/java-dcp-client/blob/master/src/test/java/examples/AirportsInFrance.java#L80

**Comment by belaazim** [comment]
+1 
thanks @daschl :)
